# Created at 2024-04-01T08:46:55.393
TestSet has not finished before stream error has appeared >> initializing exit by non-null configuration: DEFAULT
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
	at org.apache.maven.surefire.booter.MasterProcessCommand.decode(MasterProcessCommand.java:115)
	at org.apache.maven.surefire.booter.CommandReader$CommandRunnable.run(CommandReader.java:391)
	at java.base/java.lang.Thread.run(Thread.java:833)


# Created at 2024-04-01T08:46:56.169
Unexpected IOException with stream:  INFO [main] (Testbase.java:90)- Browser closed


# Created at 2024-04-01T08:46:58.092
Unexpected IOException with stream: Apr 01, 2024 8:46:58 AM org.openqa.selenium.devtools.CdpVersionFinder findNearestMatch
WARNING: Unable to find an exact match for CDP version 123, returning the closest version; found: 122; Please update to a Selenium version that supports CDP version 123


# Created at 2024-04-01T08:46:59.620
Unexpected IOException with stream:  INFO [main] (Testbase.java:76)- Browser launed with url


# Created at 2024-04-01T08:46:59.735
Unexpected IOException: 5,1,com.opencart.testlayer.LoginTest,verifyLoginTestWithValidDetails(com.opencart.testlayer.LoginTest),com.opencart.testlayer.LoginTest,null,null


# Created at 2024-04-01T08:46:59.739
Unexpected IOException with stream: Test Execution Started :- verifyLoginTestWithValidDetails


# Created at 2024-04-01T08:47:00.649
Unexpected IOException with stream:  INFO [main] (LoginTest.java:21)- on login page


# Created at 2024-04-01T08:47:01.514
Unexpected IOException with stream:  INFO [main] (LoginTest.java:26)- login details entered


# Created at 2024-04-01T08:47:01.562
Unexpected IOException with stream: My Account


# Created at 2024-04-01T08:47:01.569
Unexpected IOException with stream: Test Execution Completed :- verifyLoginTestWithValidDetails


# Created at 2024-04-01T08:47:01.570
Unexpected IOException: 6,1,com.opencart.testlayer.LoginTest,verifyLoginTestWithValidDetails(com.opencart.testlayer.LoginTest),null,null,null


# Created at 2024-04-01T08:47:02.084
Unexpected IOException with stream:  INFO [main] (Testbase.java:90)- Browser closed


# Created at 2024-04-01T08:47:02.086
Unexpected IOException with stream:  INFO [main] (Testbase.java:46)- ------------- Framework Execution Ended ---------------------


# Created at 2024-04-01T08:47:02.338
Unexpected IOException with stream: java.lang.AssertionError: expected [Your Account Has Been Created!] but found [Register Account]
	at org.testng.Assert.fail(Assert.java:111)
	at org.testng.Assert.failNotEquals(Assert.java:1578)
	at org.testng.Assert.assertEqualsImpl(Assert.java:150)
	at org.testng.Assert.assertEquals(Assert.java:132)
	at org.testng.Assert.assertEquals(Assert.java:656)
	at org.testng.Assert.assertEquals(Assert.java:666)
	at com.opencart.testlayer.RegisterTest.validateRegisteringAccountByProvidingValidAccountdetails(RegisterTest.java:34)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:819)
	at org.testng.TestRunner.run(TestRunner.java:619)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
	at org.testng.TestNG.runSuites(TestNG.java:1134)
	at org.testng.TestNG.run(TestNG.java:1101)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)



# Created at 2024-04-01T08:47:03.053
Unexpected IOException: 2,1,org.apache.maven.surefire.testng.TestNGXmlTestSuite,TestSuite,null,null,null


